### ISSUE TITLE
app gets crashed when integrate with Selligent SDK-iOS

### ISSUE THREAD

**Issue by tranvutuan** [SelligentMarketingCloud/MobileSDK-iOS#6]
I followed the instruction from the pdf for integration Selligent to our app. After clicking on the permission dialog, the app crashed at 
`[[SMManager sharedInstance] startWithLaunchOptions:launchOptions Setting:setting];`
The detail of the crash is

> [SMLib:Info]-- 160 -[SMManager startWithLaunchOptions:Setting:]
> 2019-10-23 11:42:26.822595-0400 Kobo Books[3053:1253746] +[NSFileManager libraryDirectory]: unrecognized selector sent to class 0x1b7df9fc0
> 2019-10-23 11:42:26.825101-0400 Kobo Books[3053:1253746] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSFileManager libraryDirectory]: unrecognized selector sent to class 0x1b7df9fc0' 

Are there any thoughts on it. I suspected the linking process. However, compared with the provided sample project, I dont see any difference at all.

PP: Im currently using libSelligentMobile2.0.3.a.

**Comment by tranvutuan** [comment]
Another detail for the crash is 
`2019-10-23 11:58:05.971012-0400 Kobo Books[3061:1255676] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SMManager enableInAppMessage:]: unrecognized selector sent to instance 0x14bd22770'`

**Comment by MarcBiosca** [comment]
this was solved by -> doing a -force_load on the selligent library in the linker settings
