### ISSUE TITLE
The link to the full documentation is broken

### ISSUE THREAD

**Issue by badlands** [SelligentMarketingCloud/MobileSDK-iOS#7]
This file does not exist: https://github.com/SelligentMarketingCloud/MobileSDK-iOS/blob/master/Documentation/Using%20the%20SDK.pdf

How to reproduce:
* go to https://github.com/SelligentMarketingCloud/MobileSDK-iOS/
* click on "Please check our SDK full documentation" at the bottom of the page

**Comment by Selligent** [comment]
@badlands thanks for noticing that
it has been corrected
