### ISSUE TITLE
SDK not compatible with ARM Mac Simulator

### ISSUE THREAD

**Issue by mvandervelden** [SelligentMarketingCloud/MobileSDK-iOS#9]
When trying to compile/run our app on an M1 (ARM-based architecture instead of Intel) MacBook Pro (macOS Big Sur 11.4, Xcode 12.5.1), I get this error in the linker phase:
>ld: in /PROJECT_ROOT/Pods/SelligentMobileSDK/iOS Lib/libSelligentMobile.a(SMNotifMapViewController.o), building for iOS Simulator, but linking in object file built for iOS, file '/PROJECT_ROOT/Pods/SelligentMobileSDK/iOS Lib/libSelligentMobile.a' for architecture arm64

It looks like the binaries in the sdk are not suitable for running on an arm64 simulator. This is blocking us from upgrading our development hardware. I hope this is something that can be resolved.

**Comment by Selligent** [comment]
Hi,
Could you please open a ticket in our support portal https://connect.selligent.com/) with more information about how are you adding the library in your project, if it was working before (with X software versions) or not, etc? 

We don't actively monitor github issues, however I just tested in an example app, adding the static library through cocoapods with newer big Sur version and same xcode version and it does work.

**Comment by mvandervelden** [comment]
Thanks, I asked our company contacts to report this issue with you, and I created a small sample app to reproduce the issue: https://github.com/mvandervelden/SelligentM1

Please note, this is only reproducible on Mac systems with the M1 architecture. A similar issue was reported, and fixed for the Google Analytics iOS sdk: https://github.com/firebase/firebase-ios-sdk/issues/7509

**Comment by mvandervelden** [comment]
Hi, I found out that when using the SelligentMobileSDK/Framework pod, this resolves the issue. Leaving this note here for future reference.

**Comment by MarcBiosca** [comment]
Just for the record, this is expected behavior when using the static library version, as arm64 is removed when building it for "iphonesimulator", to be able to have it for "iphoneos". The pod will be fixed to exclude this arch but still the library won't work for arm64 simulators, and indeed the solution is to use the framework version of the SDK.

**Comment by OmedMilat** [comment]
@MarcBiosca What about the React-Native wrapper? Doesn't it use the static iOS lib? I have the same error with the RN wrapper version 2.7.0.

**Comment by MarcBiosca** [comment]
@OmedMilat yes it should use the framework to avoid the issue, you should best open a ticket in our portal so the appropiate team can take this into account with the partner that built and mantains these wrappers.

**Comment by OmedMilat** [comment]
Alright, thanks for the answer @MarcBiosca
